//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisualCore.ServicioDelCore {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://google.com", ConfigurationName="ServicioDelCore.CoreWebServiceSoap")]
    public interface CoreWebServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://google.com no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://google.com/HelloWorld", ReplyAction="*")]
        VisualCore.ServicioDelCore.HelloWorldResponse HelloWorld(VisualCore.ServicioDelCore.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://google.com/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<VisualCore.ServicioDelCore.HelloWorldResponse> HelloWorldAsync(VisualCore.ServicioDelCore.HelloWorldRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://google.com", Order=0)]
        public VisualCore.ServicioDelCore.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(VisualCore.ServicioDelCore.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://google.com", Order=0)]
        public VisualCore.ServicioDelCore.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(VisualCore.ServicioDelCore.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://google.com")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CoreWebServiceSoapChannel : VisualCore.ServicioDelCore.CoreWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CoreWebServiceSoapClient : System.ServiceModel.ClientBase<VisualCore.ServicioDelCore.CoreWebServiceSoap>, VisualCore.ServicioDelCore.CoreWebServiceSoap {
        
        public CoreWebServiceSoapClient() {
        }
        
        public CoreWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CoreWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CoreWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CoreWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VisualCore.ServicioDelCore.HelloWorldResponse VisualCore.ServicioDelCore.CoreWebServiceSoap.HelloWorld(VisualCore.ServicioDelCore.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            VisualCore.ServicioDelCore.HelloWorldRequest inValue = new VisualCore.ServicioDelCore.HelloWorldRequest();
            inValue.Body = new VisualCore.ServicioDelCore.HelloWorldRequestBody();
            VisualCore.ServicioDelCore.HelloWorldResponse retVal = ((VisualCore.ServicioDelCore.CoreWebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VisualCore.ServicioDelCore.HelloWorldResponse> VisualCore.ServicioDelCore.CoreWebServiceSoap.HelloWorldAsync(VisualCore.ServicioDelCore.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<VisualCore.ServicioDelCore.HelloWorldResponse> HelloWorldAsync() {
            VisualCore.ServicioDelCore.HelloWorldRequest inValue = new VisualCore.ServicioDelCore.HelloWorldRequest();
            inValue.Body = new VisualCore.ServicioDelCore.HelloWorldRequestBody();
            return ((VisualCore.ServicioDelCore.CoreWebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
    }
}
